# Generated by Django 5.0.4 on 2024-04-25 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=32, unique=True)),
                ("course_name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curriculums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curriculum_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Degrees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoursePrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="course_toEnroll",
                        to="University.courses",
                    ),
                ),
                (
                    "prereq_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="University.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurriculumCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_level", models.IntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("First", "First Semester"),
                            ("Second", "Second Semester"),
                            ("Mid Year", "Mid Year"),
                        ],
                        default="First",
                        max_length=16,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="University.courses",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="University.curriculums",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curriculums",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="University.degrees"
            ),
        ),
        migrations.AddField(
            model_name="degrees",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="University.departments",
            ),
        ),
    ]
