# Generated by Django 5.0.4 on 2024-04-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0006_alter_studentdocuments_sd_date_uploaded"),
        ("University", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Students.studentprofile",
                    ),
                ),
                (
                    "cirruculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="University.curriculums",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_level", models.IntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("First", "First Semester"),
                            ("Second", "Second Semester"),
                            ("Mid Year", "Mid Year"),
                        ],
                        default="First",
                        max_length=16,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="University.admissions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoursesEnrolled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="University.courses",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="University.enrollments",
                    ),
                ),
            ],
        ),
    ]
