# Generated by Django 5.0.4 on 2024-04-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("University", "0002_admissions_enrollments_coursesenrolled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admissions",
            old_name="cirruculum",
            new_name="curriculum",
        ),
    ]
