# Generated by Django 5.0.4 on 2024-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("University", "0005_announcements"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcements",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
