# Generated by Django 5.0.4 on 2024-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_usersprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersprofile",
            name="user_sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
