# Generated by Django 5.0.4 on 2024-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfamilyrecords",
            name="SP_relationship",
            field=models.CharField(
                choices=[
                    ("Guardian", "Guardian"),
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Sibling", "Sibling"),
                    ("Spouse", "Spouse"),
                ],
                default="Guardian",
                max_length=16,
            ),
        ),
    ]
