# Generated by Django 5.0.4 on 2024-04-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0002_studentfamilyrecords_sp_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEducationalBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SP_education_level",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary Level"),
                            ("Secondary", "Secondary Level"),
                            ("Tertiary", "Tertiary Level"),
                            ("Vocational", "Vocational"),
                            ("Post-Graduate", "Post-Graduate"),
                        ],
                        default="Primary",
                        max_length=32,
                    ),
                ),
                ("SP_institution", models.CharField(max_length=256)),
                ("SP_address", models.CharField(max_length=256)),
                ("SP_description", models.TextField(blank=True, null=True)),
                (
                    "SP_last_year_attended",
                    models.IntegerField(
                        help_text="Year graduated or last year attended",
                        verbose_name="Year",
                    ),
                ),
                (
                    "SP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
