# Generated by Django 5.0.4 on 2024-04-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0004_documenttypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SD_document",
                    models.FileField(blank=True, null=True, upload_to="documents"),
                ),
                ("SD_date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "SD_doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Students.documenttypes",
                    ),
                ),
                (
                    "SP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
