# Generated by Django 5.0.4 on 2024-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0005_studentdocuments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocuments",
            name="SD_date_uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
