# Generated by Django 5.0.4 on 2024-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0006_alter_studentdocuments_sd_date_uploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdocuments",
            name="SD_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
